# -*- coding: utf-8 -*-
"""Level 3.ipynb

Automatically generated by Colab.

**Build a Web Scraper**
"""

import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd

url = "http://quotes.toscrape.com"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'lxml')

quotes = []
for quote_block in soup.find_all("div", class_="quote"):
    text = quote_block.find("span", class_="text").text
    author = quote_block.find("small", class_="author").text
    quotes.append({"Quote": text, "Author": author})

with open("quotes.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.DictWriter(file, fieldnames=["Quote", "Author"])
    writer.writeheader()
    writer.writerows(quotes)

print("Scraping complete. Data saved to quotes.csv")
df = pd.DataFrame(quotes)
df

"""**Create a Data Visualization Tool**"""

import pandas as pd
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

import plotly.express as px

fig = px.scatter(df, x="total_bill", y="tip", color="sex",
                 size="size", hover_data=["day", "time"],
                 title="Interactive Scatter: Total Bill vs Tip")
fig.show()

def visualize_data(df, plot_type="scatter", x=None, y=None, hue=None):
    import matplotlib.pyplot as plt
    import seaborn as sns
    import plotly.express as px

    if plot_type == "histogram":
        plt.figure(figsize=(8,5))
        plt.hist(df[x], bins=20, color='skyblue', edgecolor='black')
        plt.title(f"Distribution of {x}")
        plt.xlabel(x)
        plt.ylabel("Frequency")
        plt.show()
    elif plot_type == "box":
        plt.figure(figsize=(8,5))
        sns.boxplot(data=df, x=x, y=y, hue=hue)
        plt.title(f"{y} by {x}")
        plt.show()
    else:
        print("Plot type not supported. Choose scatter, histogram, or box.")

visualize_data(df, plot_type="scatter", x="total_bill", y="tip", hue="sex")
visualize_data(df, plot_type="histogram", x="total_bill")
visualize_data(df, plot_type="box", x="day", y="total_bill", hue="sex")

"""**Automate a Task**"""

import os
import shutil

# Step 1: Create folder for CSV files
folder_path = "/content/sales.csvs"
os.makedirs(folder_path, exist_ok=True)
print(f"Folder created: {folder_path}")

# Step 2: Sample CSV files content
csv_files = {
    "sales.csv": """Date,Region,Product,Quantity,Unit_Price
2026-01-01,North,Widget A,10,15.5
2026-01-02,South,Widget B,5,20.0
2026-01-03,East,Widget A,7,15.5
2026-01-04,West,Widget C,3,25.0
2026-01-05,North,Widget B,12,20.0
2026-01-06,South,Widget A,6,15.5"""

}

for filename, content in csv_files.items():
    file_path = os.path.join(folder_path, filename)
    with open(file_path, "w") as f:
        f.write(content)
    print(f"Created file: {filename}")
if not os.path.exists(folder_path):
    print("Folder not found!")
else:
    files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

    for file in files:
        ext = file.split('.')[-1]
        ext_folder = os.path.join(folder_path, ext.upper())

        if not os.path.exists(ext_folder):
            os.makedirs(ext_folder)

        src_path = os.path.join(folder_path, file)
        dest_path = os.path.join(ext_folder, file)
        shutil.move(src_path, dest_path)
        print(f"Moved {file} → {ext_folder}")

    print("All files organized successfully!")

from google.colab import drive
drive.mount('/content/drive')
